import iris = require('kirakira-iris');
const moderator: iris.Iris = iris.createIris({ keywords: ['示例'] });
const result: iris.KeywordResult = moderator.keywordModerate('示例');
const hit: boolean = result.hit;
const word: string | undefined = result.matchesInSource[0]?.hitWord;
const match: iris.KeywordMatch = { hitWord: '示例', start: 0, end: 2 };
const start: number | undefined = result.matchesInSource[0]?.start;
const end: number | undefined = result.matchesInNormalize[0]?.end;
moderator.refreshKeywords(['新词']);
const cleared: number = moderator.clearAIQueue();
void [hit, cleared, word, match, start, end];
